### ISSUE TITLE
Range end date

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#10]
For the last range, add an end date to the right hand side. In addition, don’t let the hover tooltip scroll off the right hand side of page.

**Comment by chillfinn** [comment]
One suggestion for the timeline/progress bar is to use more tooltip-like rollovers to reveal labels. We might also consider giving each different phase a varied colour or tone, which gives a nice clear visual distinction between them, and helps if we cannot see the label.

An example:
http://www.delhi-timeline.in/

The range is indeed a bit tricky – obviously the difficulty with trying to sync time with the position in the book, as they aren’t proportional. We might ask whether seeing it as a timeline is the problem – could it be that it’s a progress bar for the book, with labelled phases (where the date is just part for the label)?

But if it’s more important to communicate the authors work in terms of relative phases of time, perhaps we need to slightly uncouple the book progress from the timeline – or simplify the relationship. Perhaps the more page-by-page aspect is in the UV component, and we indicate the timeline progress more by, for example, just highlighting the current section of time as a whole to indicate progress.

(But if you can get the distortion tweak to work, great!)
![fullsizerender](https://user-images.githubusercontent.com/208449/30915344-6b1fb0b8-a38e-11e7-8d54-2ea2206c69b0.jpg)

**Comment by cillianjoy** [comment]
For discussion, see [https://github.com/digirati-co-uk/nui-galway-viewer/issues/11](url)
