### ISSUE TITLE
Range alignment with slider

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#11]
Can the selected range line up with the slider? For example, slider is well under ‘University’ but ‘Childhood and Schooling’ is still selected.

**Comment by tomcrane** [comment]
This is a tricky one. The viewer has a configurable setting for adjusting the labels away from their true proportional sizes, as explained here: https://github.com/digirati-co-uk/nui-galway-viewer/blob/sketches/release2.md. Setting this to 0% would fix this problem, at the expense of truncating some of the range labels. @stephenwf, anything to add here?

**Comment by chillfinn** [comment]
One suggestion for the timeline/progress bar is to use more tooltip-like rollovers to reveal labels. We might also consider giving each different phase a varied colour or tone, which gives a nice clear visual distinction between them, and helps if we cannot see the label.

An example:
http://www.delhi-timeline.in/

The range is indeed a bit tricky – obviously the difficulty with trying to sync time with the position in the book, as they aren’t proportional. We might ask whether seeing it as a timeline is the problem – could it be that it’s a progress bar for the book, with labelled phases (where the date is just part for the label)?

But if it’s more important to communicate the authors work in terms of relative phases of time, perhaps we need to slightly uncouple the book progress from the timeline – or simplify the relationship. Perhaps the more page-by-page aspect is in the UV component, and we indicate the timeline progress more by, for example, just highlighting the current section of time as a whole to indicate progress.

(But if you can get the distortion tweak to work, great!)
![fullsizerender](https://user-images.githubusercontent.com/208449/30915353-769a77ca-a38e-11e7-953f-bd3496b96b66.jpg)

**Comment by cillianjoy** [comment]
We feel the ranges should really be proportional to pages, a setting of 0%, and suggest that we remove the 'Mill Valley Politics' range (it only covers three pages anyway and it's not a major story line) for this version. Future iterations, with range hierarchy, can bring back 'Mill Valley Politics' as well as other sub-ranges. Of course the UI for this will have to be considered etc.

The idea of tooltip-like rollovers to reveal labels is good. But the timeline nav is probably best at the top and is there space for the tooltips in this case? Also, different range colours/tones would work well, I think.

**Comment by chillfinn** [comment]
We could then float the tooltip on the underside instead of at the top (so flip the shape on the x axis)

**Comment by cillianjoy** [comment]
That should work. I presume then, when active, the tooltip may cover a bit of the main viewing area of the book and the horizontal page slider, probably not a big deal.
From your drawing, I see you moved the horizontal page slider to the bottom. Do you think this works better? I think, when proportional, the navigation for ranges and pages (slider) should be displayed together?

**Comment by chillfinn** [comment]
Yes, there would be a slight overlap there, hopefully not a usability issue.
Re page navigation at bottom, it was a potential idea, if we were not able to distort the timeline and dates sync, then having them ungrouped means its doeson't matter if the pages and date ranges don't match up.

**Comment by cillianjoy** [comment]
Resolved for this version. Revisit UI later for range hierarchy.
