### ISSUE TITLE
Deep zoom on supplement panel

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#12]
Can we add deep zoom on supplement panel content? Also here, for single page content can we have no vertical scroll?

**Comment by tomcrane** [comment]
For a single image canvas we can show an OpenSeadragon panel, but I’m not clear what the interface would look like for multi-page works. Would you still expect to see more than one image on screen at once, or a paging UI similar to the main viewer (which runs the risk of confusing the two UIs)?

**Comment by cillianjoy** [comment]
Good point. After further review:
single page - deep zoom using OSD
multi-page - deep zoom using OSD with scroll bar for vertical paging? Mouse scroll over image (or +- buttons) to zoom and mouse scroll over vertical scroll bar for paging?

**Comment by tomcrane** [comment]
OSD paged vertically with scroll might be a bit odd. There's definitely a UX exercise here to come up with a good experience for the supplementary material in its modal window; I think we'll need to revisit this a bit later and do something simple for imminent launch.

OSD + vertical scroll is odd, but it would be possible to lay out a single OSD space with multiple tileSources, loading in the next IIIF Image service as its natural position is scrolled/panned into view. I'm not sure if that would be a stroke of genius UX or a confusing mess, would have to try it out.

@stephenwf @chillfinn this should be as simple as possible for now, but for future enhancement we could have a think about efficient rendering of supplemental material in a multi-page deep zoom environment - a bit like https://github.com/sul-dlss/iiifManifestLayouts if you remember that Stephen- I think there's potential in that - when viewing supplemental material the user is looking at a particular part of a larger work, and could see that part in as much detail as they like but also see the context of that part in the larger work.

**Comment by cillianjoy** [comment]
Okay, let's keep simple now. I presume that means, no OSD on supplementary material with the 'View in repo' link option providing deep zoom (as a new window). We'll have the supplementary material in our repo with deep zoom anyway.
