### ISSUE TITLE
On first/initial view

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#15]
Can the default page, the first page the viewer opens, be the title page or a marketing graphic we have?
Display a message that describes how you can interact with the ranges to navigate the book. When a user engages with the viewer the message quickly fades.
For example, see http://projects.propublica.org/louisiana/#delacroix (a user message appears on the timeline on first view).

**Comment by tomcrane** [comment]
The way to do this is to set `startCanvas` in the manifest (see http://iiif.io/api/presentation/2.1/#startcanvas) – I have added this in: https://github.com/digirati-co-uk/nui-galway-viewer/blob/sketches/manifest-wip.json#L10

What we can’t do in vanilla IIIF is specify the start message, that will have to be a feature of the viewer. So to make this work we need the viewer to jump to startCanvas (if present) and show its configured initialisation message on loading.

**Comment by cillianjoy** [comment]
startCanvas will work well for starting on the canvas we define. 
Another suggestion for a message is to add an icon to the viewer for more information. Not sure, maybe all we need, if at all, is a user message on first view like http://projects.propublica.org/louisiana/#delacroix. Part of the viewer as you said.

**Comment by tomcrane** [comment]
An "about" panel, that can be configured to show on first load (remembering this via cookie), but can be re-shown on demand by clicking an info icon ⓘ

**Comment by cillianjoy** [comment]
For launch we just need to define the startCanvas, which we can do via the manifest. Let's take the simplest option to display about/user message/information, this may be a viewer user message on first view and later an about panel. Your call on what's doable for launch.
