### ISSUE TITLE
Hierarchical ranges in timeline

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/nui-galway-viewer#26]
Requires UX first

Need to be able to display child ranges.

@cillianjoy suggests Gantt chart style approach. @chillfinn to think about UX.

**Comment by tomcrane** [comment]
> Currently, we use 8 ranges and we want to display a hierarchy of ~50 ranges with ~8 top level ranges.

**Comment by chillfinn** [comment]
Key here will be seeing the data for the child ranges (ie is there overlap, length of labels etc)

**Comment by tomcrane** [comment]
Once ranges are hierarchical, the structure becomes even more divorced from the temporal coverage. Consider a range whose main temporal coverage is 1880-1900, but that contains a child range with coverage 1910-1911 (a forward reference in a memoir, suitable for highlighting as a child range but not at the top level). Any attempt to plot these on a timeline but still convey parent-child relationships would make for a messy UI.

I think that the pure timeline view (time-relative) is simply an alternative view, which you can switch on and off, and not the default view. We can investigate this.

**Comment by cillianjoy** [comment]
Data is in progress. I'll share when complete and we can take it from there.

**Comment by cillianjoy** [comment]
First draft of range data https://nuigalwayie-my.sharepoint.com/personal/0114659s_nuigalway_ie/_layouts/15/guestaccess.aspx?docid=16f72bbe1464d4e7d9b490726436afe16&authkey=AURe8siIlNCeFXW0jFEU8Co&e=41b57bec4eb94582a8a8534c41543050.
It can still be cut down further, revised, and reworded/shortened (if required).
