### ISSUE TITLE
Touch interface improvements

### ISSUE THREAD

**Issue by tomcrane** [digirati-co-uk/nui-galway-viewer#30]
(To be elaborated)

The small device view works, but what about the large touch device? You can't hover over the other timeline elements.

**Comment by tomcrane** [comment]
Consider access to small screen list mode on large touch devices too

**Comment by tomcrane** [comment]
Non-interactive version of top bar (always visible on touch)

List-version of timeline similar to small screen device (but has to accommodate hierarchical nav)

How do you know what to do?

**Comment by cillianjoy** [comment]
Related [https://github.com/digirati-co-uk/nui-galway-viewer/issues/46](url)
