### ISSUE TITLE
Small screen paging arrows overlay callout links

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#46]
On small screen, the pagination arrows can overlay callout links and get in way of user selection of callout links.

**Comment by stephenwf** [comment]
@cillianjoy @chillfinn Would scaling down the hitbox for mobile devices work?

<img width="428" alt="screen shot 2017-12-08 at 10 10 18" src="https://user-images.githubusercontent.com/8266711/33761265-4830c4e8-dc00-11e7-8f9c-60df87054f85.png">


Alternatively we could move the controls on mobile. We've done something like this on Wellcomes Bedlam project: https://digirati-co-uk.github.io/wellcome-quilt-prototype/bedlam-retreat.html#image

**Comment by chillfinn** [comment]
We should definitely consider moving them. Another suggestion was to enable swiping left and right, but then we'd need to consider not interfering with zooming and manipulating the image.
