### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#8]
Paging should reflect pages rather than images. For example:
Image – Page (user display)
Image 1 – Front cover
Image 2 – Title page
Image 3 – Page 1 of 175
Image 4 – Page 2 of 175
…
…
…
Third last image – Page 175 of 175
Second last image – Map insert of birth place
Last image – Back cover

**Comment by tomcrane** [comment]
Currently we display the canvas label property, and a generated “x of y” string from a 1-based count of the canvases. We could introduce a configuration setting that dropped the generated part altogether, so if you can get the labels populated we would just display those. That’s really the only reliable way of having “Page 1 of 175” where that isn’t really the first page. That is, you would add to the manifest labels such that the third canvas has:

“label”: “Page 1 of 175”

…and so on. The viewer would only display these labels and not any generated label.
