### ISSUE TITLE
Range hover

### ISSUE THREAD

**Issue by cillianjoy** [digirati-co-uk/nui-galway-viewer#9]
When you hover over a range the text is expanded. Can we distinguish between the ranges in this case. This is probably a simple CSS change that NUIG can do later.

**Comment by tomcrane** [comment]
@stephenwf, should be straightforward to differentiate with hover colour?

**Comment by stephenwf** [comment]
Yes shouldn't be a problem

**Comment by chillfinn** [comment]
One suggestion for the timeline/progress bar is to use more tooltip-like rollovers to reveal labels. We might also consider giving each different phase a varied colour or tone, which gives a nice clear visual distinction between them, and helps if we cannot see the label.
 
An example:
http://www.delhi-timeline.in/
 
The range is indeed a bit tricky – obviously the difficulty with trying to sync time with the position in the book, as they aren’t proportional. We might ask whether seeing it as a timeline is the problem – could it be that it’s a progress bar for the book, with labelled phases (where the date is just part for the label)?
 
But if it’s more important to communicate the authors work in terms of relative phases of time, perhaps we need to slightly uncouple the book progress from the timeline – or simplify the relationship. Perhaps the more page-by-page aspect is in the UV component, and we indicate the timeline progress more by, for example, just highlighting the current section of time as a whole to indicate progress.
 
(But if you can get the distortion tweak to work, great!)
![fullsizerender](https://user-images.githubusercontent.com/208449/30915290-3f4b4ace-a38e-11e7-89ad-d12086f49223.jpg)

**Comment by cillianjoy** [comment]
For discussion, see [https://github.com/digirati-co-uk/nui-galway-viewer/issues/11](url)
